# Generated by Django 2.2.3 on 2019-08-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_description',
            field=models.CharField(max_length=255, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('10_normal', 'Normal'), ('Normal', 'High'), ('Critical', 'Critical'), ('Blocker', 'Blocker')], default='Normal', max_length=20, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Blocked', 'Blocked'), ('Done', 'Done'), ('Dismissed', 'Dismissed')], default='To Do', max_length=10),
        ),
    ]
