# Generated by Django 2.2.3 on 2019-08-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20190808_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('Normal', 'High'), ('Critical', 'Critical'), ('Blocker', 'Blocker')], default='Normal', max_length=20, verbose_name='priority'),
        ),
    ]
